#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user_index:
    path: /user
    controller: App\Controller\UserController::index
home:
    path: /home
    controller: App\Controller\HomeController::index
login:
    path: /login
    controller: App\Controller\SecurityController::index
wallet:
    path: /wallet
    methods: ['GET', 'POST']
    defaults:
        _controller: 'App\Controller\WalletController::index'
        userRepository: '@App\Repository\UserRepository'
app_wallet_show:
    path: /wallets/{id}
    controller: App\Controller\WalletController::show
app_wallet_delete:
    path: /wallets/{id}
    controller: App\Controller\WalletController::delete
app_wallet_edit:
    path: /wallets/{id}
    controller: App\Controller\WalletController::edit
