# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    productpicture_directory: '%kernel.project_dir%/public/uploads/images'

services:
# Alias the Doctrine\Persistence\ObjectManager interface to the default_entity_manager service
    Doctrine\Persistence\ObjectManager:
        alias: doctrine.orm.default_entity_manager
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
     
    neutrino_api_client:
        class: GuzzleHttp\Client
        arguments:
            - base_uri: 'https://neutrinoapi.com'
              headers:
                  User-Agent: '007007'
                  API-Key: 'SDP4TUoFlxnmnSHz6kTHBD33OOwgMOO4aWwiE1eaL9MiQ6Aw'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

parameters:
    facebook_app_id: '896984404840648'
    facebook_app_secret: '7e8881a62e20ae95994132bc285f0365'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

services:
    App\Controller\SecurityController:
        arguments:
            $authenticationUtils: '@Symfony\Component\Security\Http\Authentication\AuthenticationUtils'
    App\Controller\RegistrationController:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $mailer: '@swiftmailer.mailer.default'
        tags: ['controller.service_arguments']
    
    
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
